apiVersion: v1
kind: Secret
metadata:
  name: site-secrets
  namespace: crypto-hound
type: Opaque
stringData:
  stripe_secret: sk_live_xxx
  stripe_webhook_secret: whsec_xxx
  stripe_price_id: price_xxx
  public_url: https://crypto-hound.io
